AVAILABLE_COMMUNES = [
  "Cerro Navia",
  "Colina",
  "Conchalí",
  "Estación Central",
  "Huechuraba",
  "Independencia",
  "La Cisterna",
  "La Florida",
  "La Granja",
  "La Reina",
  "Las Condes",
  "Lo Barnechea",
  "Lo Espejo",
  "Macul",
  "Ñuñoa",
  "Pedro Aguirre Cerda",
  "Peñalolén",
  "Providencia",
  "Recoleta",
  "San Joaquín",
  "San Miguel",
  "San Ramón",
  "Santiago Centro",
  "Vitacura"
]
